apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: newsvine-article-consumer
  namespace: streaming
spec:
  type: Python
  mode: cluster
  image: apache/spark:3.5.1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/work-dir/streaming/spark_article_consumer.py
  sparkVersion: 3.5.1
  restartPolicy:
    type: OnFailure
    onFailureRetries: 5
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    memory: 1g
    serviceAccount: spark
  executor:
    instances: 1
    cores: 1
    memory: 2g
  deps:
    pyFiles: []
  sparkConf:
    spark.kubernetes.container.image: apache/spark:3.5.1
  arguments: []
